/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package exament3;

import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class VentanaIconos extends javax.swing.JFrame {

    Random generadorLetras = new Random();
    int num1;
    int num2;
    int num3;
    int num4;
    int num5;
    int num6;
    int num7;
    int num8;
    int num9;
    int num10;
    int num11;
    int num12;
    int num13;
    int num14;
    int num15;
    int num16;
    //ImageIcon icono1 =  new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/A.png"))));

    public VentanaIconos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMuestra = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanelBotonIcono = new javax.swing.JPanel();
        jToggleButtonI9 = new javax.swing.JToggleButton();
        jToggleButtonI1 = new javax.swing.JToggleButton();
        jToggleButtonI13 = new javax.swing.JToggleButton();
        jToggleButtonI3 = new javax.swing.JToggleButton();
        jToggleButtonI4 = new javax.swing.JToggleButton();
        jToggleButtonI14 = new javax.swing.JToggleButton();
        jToggleButtonI11 = new javax.swing.JToggleButton();
        jToggleButtonI10 = new javax.swing.JToggleButton();
        jToggleButtonI16 = new javax.swing.JToggleButton();
        jToggleButtonI12 = new javax.swing.JToggleButton();
        jToggleButtonI5 = new javax.swing.JToggleButton();
        jToggleButtonI2 = new javax.swing.JToggleButton();
        jToggleButtonI15 = new javax.swing.JToggleButton();
        jToggleButtonI7 = new javax.swing.JToggleButton();
        jToggleButtonI6 = new javax.swing.JToggleButton();
        jToggleButtonI8 = new javax.swing.JToggleButton();
        jPanelBotones = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        javax.swing.GroupLayout jPanelMuestraLayout = new javax.swing.GroupLayout(jPanelMuestra);
        jPanelMuestra.setLayout(jPanelMuestraLayout);
        jPanelMuestraLayout.setHorizontalGroup(
            jPanelMuestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMuestraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanelMuestraLayout.setVerticalGroup(
            jPanelMuestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMuestraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMuestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToggleButtonI9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N
        jToggleButtonI9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonI9ActionPerformed(evt);
            }
        });

        jToggleButtonI1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N
        jToggleButtonI1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonI1ActionPerformed(evt);
            }
        });

        jToggleButtonI13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N
        jToggleButtonI13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonI13ActionPerformed(evt);
            }
        });

        jToggleButtonI3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N
        jToggleButtonI3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonI3ActionPerformed(evt);
            }
        });

        jToggleButtonI4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N
        jToggleButtonI4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonI4ActionPerformed(evt);
            }
        });

        jToggleButtonI14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N
        jToggleButtonI14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonI14ActionPerformed(evt);
            }
        });

        jToggleButtonI11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N
        jToggleButtonI11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonI11ActionPerformed(evt);
            }
        });

        jToggleButtonI10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N
        jToggleButtonI10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonI10ActionPerformed(evt);
            }
        });

        jToggleButtonI16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N
        jToggleButtonI16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonI16ActionPerformed(evt);
            }
        });

        jToggleButtonI12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N
        jToggleButtonI12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonI12ActionPerformed(evt);
            }
        });

        jToggleButtonI5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N
        jToggleButtonI5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonI5ActionPerformed(evt);
            }
        });

        jToggleButtonI2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jToggleButtonI15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N
        jToggleButtonI15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonI15ActionPerformed(evt);
            }
        });

        jToggleButtonI7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N
        jToggleButtonI7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonI7ActionPerformed(evt);
            }
        });

        jToggleButtonI6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N
        jToggleButtonI6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonI6ActionPerformed(evt);
            }
        });

        jToggleButtonI8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N
        jToggleButtonI8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonI8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotonIconoLayout = new javax.swing.GroupLayout(jPanelBotonIcono);
        jPanelBotonIcono.setLayout(jPanelBotonIconoLayout);
        jPanelBotonIconoLayout.setHorizontalGroup(
            jPanelBotonIconoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonIconoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotonIconoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBotonIconoLayout.createSequentialGroup()
                        .addGroup(jPanelBotonIconoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelBotonIconoLayout.createSequentialGroup()
                                .addComponent(jToggleButtonI1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButtonI2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelBotonIconoLayout.createSequentialGroup()
                                .addComponent(jToggleButtonI5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButtonI7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBotonIconoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jToggleButtonI3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButtonI6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBotonIconoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButtonI4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButtonI8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelBotonIconoLayout.createSequentialGroup()
                        .addComponent(jToggleButtonI9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButtonI10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButtonI11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButtonI12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBotonIconoLayout.createSequentialGroup()
                        .addComponent(jToggleButtonI13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButtonI14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButtonI15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButtonI16, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBotonIconoLayout.setVerticalGroup(
            jPanelBotonIconoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonIconoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotonIconoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelBotonIconoLayout.createSequentialGroup()
                        .addGroup(jPanelBotonIconoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButtonI1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButtonI2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButtonI3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButtonI4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelBotonIconoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jToggleButtonI5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButtonI7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jToggleButtonI6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jToggleButtonI8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBotonIconoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelBotonIconoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jToggleButtonI9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jToggleButtonI11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jToggleButtonI12, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jToggleButtonI10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelBotonIconoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButtonI13, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonI14, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonI15, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonI16, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotonesLayout = new javax.swing.GroupLayout(jPanelBotones);
        jPanelBotones.setLayout(jPanelBotonesLayout);
        jPanelBotonesLayout.setHorizontalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanelBotonesLayout.setVerticalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelBotonIcono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBotonIcono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonI4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonI4ActionPerformed
    }//GEN-LAST:event_jToggleButtonI4ActionPerformed

    private void jToggleButtonI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonI1ActionPerformed
    }//GEN-LAST:event_jToggleButtonI1ActionPerformed

    private void jToggleButtonI3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonI3ActionPerformed
    }//GEN-LAST:event_jToggleButtonI3ActionPerformed

    private void jToggleButtonI5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonI5ActionPerformed
    }//GEN-LAST:event_jToggleButtonI5ActionPerformed

    private void jToggleButtonI6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonI6ActionPerformed
    }//GEN-LAST:event_jToggleButtonI6ActionPerformed

    private void jToggleButtonI7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonI7ActionPerformed
    }//GEN-LAST:event_jToggleButtonI7ActionPerformed

    private void jToggleButtonI8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonI8ActionPerformed
    }//GEN-LAST:event_jToggleButtonI8ActionPerformed

    private void jToggleButtonI9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonI9ActionPerformed
    }//GEN-LAST:event_jToggleButtonI9ActionPerformed

    private void jToggleButtonI10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonI10ActionPerformed
    }//GEN-LAST:event_jToggleButtonI10ActionPerformed

    private void jToggleButtonI11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonI11ActionPerformed
    }//GEN-LAST:event_jToggleButtonI11ActionPerformed

    private void jToggleButtonI12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonI12ActionPerformed
    }//GEN-LAST:event_jToggleButtonI12ActionPerformed

    private void jToggleButtonI13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonI13ActionPerformed
    }//GEN-LAST:event_jToggleButtonI13ActionPerformed

    private void jToggleButtonI14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonI14ActionPerformed
    }//GEN-LAST:event_jToggleButtonI14ActionPerformed

    private void jToggleButtonI15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonI15ActionPerformed
    }//GEN-LAST:event_jToggleButtonI15ActionPerformed

    private void jToggleButtonI16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonI16ActionPerformed
    }//GEN-LAST:event_jToggleButtonI16ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        char letra;
        for (int contador = 0; contador < 16; contador++) {




            jToggleButtonI1.setEnabled(true);
            jToggleButtonI2.setEnabled(true);
            jToggleButtonI3.setEnabled(true);
            jToggleButtonI4.setEnabled(true);
            jToggleButtonI5.setEnabled(true);
            jToggleButtonI6.setEnabled(true);
            jToggleButtonI7.setEnabled(true);
            jToggleButtonI8.setEnabled(true);
            jToggleButtonI9.setEnabled(true);
            jToggleButtonI10.setEnabled(true);
            jToggleButtonI11.setEnabled(true);
            jToggleButtonI12.setEnabled(true);
            jToggleButtonI13.setEnabled(true);
            jToggleButtonI14.setEnabled(true);
            jToggleButtonI15.setEnabled(true);
            jToggleButtonI16.setEnabled(true);

            num1 = (generadorLetras.nextInt(16) + 65);
            num2 = (generadorLetras.nextInt(16) + 65);
            num3 = (generadorLetras.nextInt(16) + 65);
            num4 = (generadorLetras.nextInt(16) + 65);
            num5 = (generadorLetras.nextInt(16) + 65);
            num6 = (generadorLetras.nextInt(16) + 65);
            num7 = (generadorLetras.nextInt(16) + 65);
            num8 = (generadorLetras.nextInt(16) + 65);
            num9 = (generadorLetras.nextInt(16) + 65);
            num10 = (generadorLetras.nextInt(16) + 65);
            num11 = (generadorLetras.nextInt(16) + 65);
            num12 = (generadorLetras.nextInt(16) + 65);
            num13 = (generadorLetras.nextInt(16) + 65);
            num14 = (generadorLetras.nextInt(16) + 65);
            num15 = (generadorLetras.nextInt(16) + 65);
            num16 = (generadorLetras.nextInt(16) + 65);


            try {
                jToggleButtonI1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + (char) num1 + ".png"))));
                jToggleButtonI2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + (char) num2 + ".png"))));
                jToggleButtonI3.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + (char) num3 + ".png"))));
                jToggleButtonI4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + (char) num4 + ".png"))));
                jToggleButtonI5.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + (char) num5 + ".png"))));
                jToggleButtonI6.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + (char) num6 + ".png"))));
                jToggleButtonI7.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + (char) num7 + ".png"))));
                jToggleButtonI8.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + (char) num8 + ".png"))));
                jToggleButtonI9.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + (char) num9 + ".png"))));
                jToggleButtonI10.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + (char) num10 + ".png"))));
                jToggleButtonI11.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + (char) num11 + ".png"))));
                jToggleButtonI12.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + (char) num12 + ".png"))));
                jToggleButtonI13.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + (char) num13 + ".png"))));
                jToggleButtonI14.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + (char) num14 + ".png"))));
                jToggleButtonI15.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + (char) num15 + ".png"))));
                jToggleButtonI16.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + (char) num16 + ".png"))));
            } catch (IOException ex) {
                Logger.getLogger(VentanaIconos.class.getName()).log(Level.SEVERE, null, ex);
            }


        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        for (int contador = 0; contador < 16; contador++) {

            jToggleButtonI1.setEnabled(false);
            jToggleButtonI2.setEnabled(false);
            jToggleButtonI3.setEnabled(false);
            jToggleButtonI4.setEnabled(false);
            jToggleButtonI5.setEnabled(false);
            jToggleButtonI6.setEnabled(false);
            jToggleButtonI7.setEnabled(false);
            jToggleButtonI8.setEnabled(false);
            jToggleButtonI9.setEnabled(false);
            jToggleButtonI10.setEnabled(false);
            jToggleButtonI11.setEnabled(false);
            jToggleButtonI12.setEnabled(false);
            jToggleButtonI13.setEnabled(false);
            jToggleButtonI14.setEnabled(false);
            jToggleButtonI15.setEnabled(false);
            jToggleButtonI16.setEnabled(false);

            jToggleButtonI1.setSelected(false);
            jToggleButtonI2.setSelected(false);
            jToggleButtonI3.setSelected(false);
            jToggleButtonI4.setSelected(false);
            jToggleButtonI5.setSelected(false);
            jToggleButtonI6.setSelected(false);
            jToggleButtonI7.setSelected(false);
            jToggleButtonI8.setSelected(false);
            jToggleButtonI9.setSelected(false);
            jToggleButtonI10.setSelected(false);
            jToggleButtonI11.setSelected(false);
            jToggleButtonI12.setSelected(false);
            jToggleButtonI13.setSelected(false);
            jToggleButtonI14.setSelected(false);
            jToggleButtonI15.setSelected(false);
            jToggleButtonI16.setSelected(false);

            num1 = (generadorLetras.nextInt(16) + 65);
            num2 = (generadorLetras.nextInt(16) + 65);
            num3 = (generadorLetras.nextInt(16) + 65);
            num4 = (generadorLetras.nextInt(16) + 65);

            try {
                jLabel1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + (char) num1 + ".png"))));
                jLabel2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + (char) num2 + ".png"))));
                jLabel3.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + (char) num3 + ".png"))));
                jLabel4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/" + (char) num4 + ".png"))));
                
            } catch (IOException ex) {
                Logger.getLogger(VentanaIconos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaIconos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaIconos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaIconos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaIconos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaIconos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelBotonIcono;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelMuestra;
    private javax.swing.JToggleButton jToggleButtonI1;
    private javax.swing.JToggleButton jToggleButtonI10;
    private javax.swing.JToggleButton jToggleButtonI11;
    private javax.swing.JToggleButton jToggleButtonI12;
    private javax.swing.JToggleButton jToggleButtonI13;
    private javax.swing.JToggleButton jToggleButtonI14;
    private javax.swing.JToggleButton jToggleButtonI15;
    private javax.swing.JToggleButton jToggleButtonI16;
    private javax.swing.JToggleButton jToggleButtonI2;
    private javax.swing.JToggleButton jToggleButtonI3;
    private javax.swing.JToggleButton jToggleButtonI4;
    private javax.swing.JToggleButton jToggleButtonI5;
    private javax.swing.JToggleButton jToggleButtonI6;
    private javax.swing.JToggleButton jToggleButtonI7;
    private javax.swing.JToggleButton jToggleButtonI8;
    private javax.swing.JToggleButton jToggleButtonI9;
    // End of variables declaration//GEN-END:variables
}
